version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123 # Senha do usuário root
      MYSQL_DATABASE: seu_banco_de_dados # Nome do banco de dados
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql # Nome do serviço MySQL
      PMA_USER: root
      PMA_PASSWORD: 123
    depends_on:
      - mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./meu-app:/var/www/html
    ports:
      - "80:80"

volumes:
  db_data:
